# https://github.com/fluid-dev/hexo-theme-fluid/blob/master/_config.yml

# Site
favicon: /assets/basic/favicon.png
# Site

# header
navbar:
    blog_title: 'Blog'
# header

# footer
footer:
    content: '<div>isFooter</div>'
    statistics:
        enable: true
        source: "leancloud"  # 可选 leancloud | busuanzi  根据自己需求选择
        pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
        uv_format: "总访客数 {} 人"
# footer

# web_analytics
web_analytics: # 网页访问统计
    enable: true # 默认为false，启用网页统计改为true即可
    leancloud: # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
        app_id: 15XCL0pFCCAWeeWt9YczoDFU-gzGzoHsz
        app_key: wuRzmMS26dHWKe2TTVQQkglM
        server_url: https://15xcl0pf.lc-cn-n1-shared.com
# web_analytics

# Page - about
about:
    avatar: /assets/basic/avatar.png
    name: 'pocky'
    intro: '程序员'
    icons:
        - {
              class: 'iconfont icon-github-fill',
              link: 'https://github.com/2460392754',
              tip: 'GitHub',
          }
        - {
              class: 'iconfont icon-book',
              link: 'https://juejin.cn/user/413072102264487',
              tip: '稀土掘金',
          }
        - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }
# Page - about
