code:
    copy_btn: true
    highlight:
        enable: true
        line_number: true
        lib: 'highlightjs'
        highlightjs:
            style: 'Github Gist'
            bg_color: false
        prismjs:
            style: 'default'
            preprocess: true
